//jsonData.js

let json = `[{"id":1,"first_name":"Brock","last_name":"Westbrook","email":"bwestbrook0@aol.com","gender":"Male","salary":6846},
{"id":2,"first_name":"Ernie","last_name":"Bolus","email":"ebolus1@google.de","gender":"Male","salary":8696},
{"id":3,"first_name":"Edlin","last_name":"Tesimon","email":"etesimon2@delicious.com","gender":"Male","salary":2896},
{"id":4,"first_name":"Gwenni","last_name":"Bouller","email":"gbouller3@yelp.com","gender":"Genderqueer","salary":4323},
{"id":5,"first_name":"Marena","last_name":"Timmins","email":"mtimmins4@bbc.co.uk","gender":"Female","salary":2025},
{"id":6,"first_name":"Steffane","last_name":"Hammill","email":"shammill5@acquirethisname.com","gender":"Female","salary":8314},
{"id":7,"first_name":"Lorraine","last_name":"Jonk","email":"ljonk6@globo.com","gender":"Female","salary":8346},
{"id":8,"first_name":"Bendick","last_name":"Castles","email":"bcastles7@boston.com","gender":"Male","salary":5790},
{"id":9,"first_name":"Evelin","last_name":"Hudson","email":"ehudson8@mashable.com","gender":"Male","salary":8405},
{"id":10,"first_name":"Meredeth","last_name":"Giamelli","email":"mgiamelli9@un.org","gender":"Male","salary":6419},
{"id":11,"first_name":"Coletta","last_name":"Nesbit","email":"cnesbita@cnn.com","gender":"Female","salary":6437},
{"id":12,"first_name":"Micky","last_name":"Bilton","email":"mbiltonb@canalblog.com","gender":"Female","salary":3659},
{"id":13,"first_name":"Clay","last_name":"Perigeaux","email":"cperigeauxc@lycos.com","gender":"Male","salary":6680},
{"id":14,"first_name":"Nero","last_name":"Matson","email":"nmatsond@hugedomains.com","gender":"Male","salary":6242},
{"id":15,"first_name":"Tyler","last_name":"Gerrietz","email":"tgerrietze@hubpages.com","gender":"Male","salary":2830},
{"id":16,"first_name":"Claretta","last_name":"Chafney","email":"cchafneyf@barnesandnoble.com","gender":"Female","salary":5170},
{"id":17,"first_name":"Gualterio","last_name":"O' Liddy","email":"goliddyg@blinklist.com","gender":"Male","salary":3716},
{"id":18,"first_name":"Sonya","last_name":"Crowe","email":"scroweh@slashdot.org","gender":"Female","salary":3599},
{"id":19,"first_name":"Jennie","last_name":"Ewols","email":"jewolsi@163.com","gender":"Female","salary":6825},
{"id":20,"first_name":"Lorna","last_name":"Esch","email":"leschj@photobucket.com","gender":"Female","salary":8246}]`;